# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621365806935b800595cba725e48f52e9ab53bbafbede886c09059f9dae3d6fe83f7718054241890610c8fefb64deaa0400757f874d7ea744c54a7da82756840

test:
  secret_key_base: eb84eae5c9afc69766115f8a7b8477ba1166d208d0152d870a3c77231880cd53dccfe663c8fe0636aad44d1eb3556c4f0548b48136b932a2d39717d1be1001ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
